# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Django My Way

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest tox wheel
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest
    - name: Test with tox
      run: |
        tox

  test_generate:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        script:
          - name: SQLite
            args: "database=SQLite windows=n"
          - name: PostgreSQL
            args: "database=PostgreSQL windows=n"

    services:
      postgres:
        image: postgres:12
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres

    env:
      DATABASE_URL: "postgres://postgres:postgres@localhost:5432/postgres"

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Test generated project (${{ matrix.script.name }})
      run: |
        sh tests/test_bare.sh ${{ matrix.script.args }}
